# Generated by Django 5.0.3 on 2024-03-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("stock", models.IntegerField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="books")),
                ("published", models.DateField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
            ],
        ),
    ]
