# Generated by Django 5.0.3 on 2024-03-08 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn_10", models.CharField(blank=True, max_length=10, null=True)),
                ("isbn_13", models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="number",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="books.booknumber",
            ),
        ),
    ]
