# Generated by Django 5.0.3 on 2024-03-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_character"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                (
                    "books",
                    models.ManyToManyField(related_name="authors", to="books.book"),
                ),
            ],
        ),
    ]
